M1-G1-Admin/Controllers/CombosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using M1_G1_Admin.Models;
using M1_G1_Admin.Pages;

namespace M1_G1_Admin.Controllers
{
    public class CombosController : Controller
    {
        private readonly RestaurantContext _context;

        public CombosController(RestaurantContext context)
        {
            _context = context;
        }

        // GET: Combos
        public async Task<IActionResult> Index()
        {
            return View(await _context.combos.ToListAsync());
        }

        // GET: Combos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var combos = await _context.combos
                .FirstOrDefaultAsync(m => m.combo_id == id);
            if (combos == null)
            {
                return NotFound();
            }

            return View(combos);
        }

        // GET: Combos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Combos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("combo_id,nombre,descripcion,precio,disponible")] Combos combos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(combos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(combos);
        }

        // GET: Combos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var combos = await _context.combos.FindAsync(id);
            if (combos == null)
            {
                return NotFound();
            }
            return View(combos);
        }

        // POST: Combos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("combo_id,nombre,descripcion,precio,disponible")] Combos combos)
        {
            if (id != combos.combo_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(combos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CombosExists(combos.combo_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(combos);
        }

        // GET: Combos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var combos = await _context.combos
                .FirstOrDefaultAsync(m => m.combo_id == id);
            if (combos == null)
            {
                return NotFound();
            }

            return View(combos);
        }

        // POST: Combos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var combos = await _context.combos.FindAsync(id);
            if (combos != null)
            {
                _context.combos.Remove(combos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Combos/Add
        public async Task<IActionResult> Add(int id)
        {
            var combo = await _context.combos.FindAsync(id);
            
            if (combo == null)
                return NotFound();
            var platosCombo = await _context.combos_platos
                .Where(combo => combo.combo_id == id)
                .Select(combo => combo.plato_id)
                .ToListAsync();
 
            AgregarPlatos agregarPlatos = new AgregarPlatos();
            agregarPlatos.combo = combo;
            
            agregarPlatos.platos = await _context
                .platos
                .Where(pt => !platosCombo.Contains(pt.plato_id))
                .ToListAsync();

            agregarPlatos.platosXCombo = await _context
                .platos
                .Where(p => platosCombo.Contains(p.plato_id))
                .ToListAsync();
            
            return View(agregarPlatos);
        }

        [HttpPost, ActionName("AddPlato")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPlato(int plato, int idCombo)
        {
            
            try
            {
                CombosPlatos combPlato = new CombosPlatos();
                combPlato.combo_id = idCombo;
                combPlato.plato_id = plato;

                _context.combos_platos.Add(combPlato);
                await _context.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
            
            return RedirectToAction(nameof(Add), new { id = idCombo });
        }

        private bool CombosExists(int id)
        {
            return _context.combos.Any(e => e.combo_id == id);
        }
    }
}

M1-G1-Admin/Controllers/MesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using M1_G1_Admin.Models;

namespace M1_G1_Admin.Controllers
{
    public class MesasController : Controller
    {
        private readonly RestaurantContext _context;

        public MesasController(RestaurantContext context)
        {
            _context = context;
        }

        // GET: Mesas
        public async Task<IActionResult> Index()
        {
            return View(await _context.mesa.ToListAsync());
        }

        // GET: Mesas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesa = await _context.mesa
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesa == null)
            {
                return NotFound();
            }

            return View(mesa);
        }

        // GET: Mesas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mesas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,numero_asientos,numero_mesa,estado_mesa")] Mesa mesa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mesa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mesa);
        }

        // GET: Mesas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesa = await _context.mesa.FindAsync(id);
            if (mesa == null)
            {
                return NotFound();
            }
            return View(mesa);
        }

        // POST: Mesas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,numero_asientos,numero_mesa,estado_mesa")] Mesa mesa)
        {
            if (id != mesa.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mesa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MesaExists(mesa.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mesa);
        }

        // GET: Mesas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesa = await _context.mesa
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesa == null)
            {
                return NotFound();
            }

            return View(mesa);
        }

        // POST: Mesas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mesa = await _context.mesa.FindAsync(id);
            if (mesa != null)
            {
                _context.mesa.Remove(mesa);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MesaExists(int id)
        {
            return _context.mesa.Any(e => e.id == id);
        }
    }
}

M1-G1-Admin/Controllers/PlatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using M1_G1_Admin.Models;

namespace M1_G1_Admin.Controllers
{
    public class PlatosController : Controller
    {
        private readonly RestaurantContext _context;

        public PlatosController(RestaurantContext context)
        {
            _context = context;
        }

        // GET: Platos
        public async Task<IActionResult> Index()
        {
            return View(await _context.platos.ToListAsync());
        }

        // GET: Platos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var platos = await _context.platos
                .FirstOrDefaultAsync(m => m.plato_id == id);
            if (platos == null)
            {
                return NotFound();
            }

            return View(platos);
        }

        // GET: Platos/Create
        public IActionResult Create()
        {
            ViewBag.Categoria = _context.categorias_platos.ToList();

            return View();
        }

        // POST: Platos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("plato_id,nombre,descripcion,precio,disponible,categoria_id,es_bebida")] Platos platos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(platos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(platos);
        }

        // GET: Platos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var platos = await _context.platos.FindAsync(id);
            if (platos == null)
            {
                return NotFound();
            }
            ViewBag.Categoria = await _context.categorias_platos.ToListAsync();
            return View(platos);
        }

        // POST: Platos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("plato_id,nombre,descripcion,precio,disponible,categoria_id,es_bebida")] Platos platos)
        {
            if (id != platos.plato_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(platos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlatosExists(platos.plato_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(platos);
        }

        // GET: Platos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var platos = await _context.platos
                .FirstOrDefaultAsync(m => m.plato_id == id);
            if (platos == null)
            {
                return NotFound();
            }

            return View(platos);
        }

        // POST: Platos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var platos = await _context.platos.FindAsync(id);
            if (platos != null)
            {
                _context.platos.Remove(platos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlatosExists(int id)
        {
            return _context.platos.Any(e => e.plato_id == id);
        }
    }
}

M1-G1-Admin/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - M1_G1_Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<style>
    .content {
        flex: 1;
    }</style>
<body class="bg-dark">
    <div class="d-flex">
        <div class="content w-100 h-100">
            <section class="p-3 ">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <footer class="border-top footer text-muted ">
        <div class="container">
            <div class="container">
                <div class="row text">
                    <div class="col">CARLOS LEONEL CASTANEDA HERNANDEZ</div>
                    <div class="col">LAURA LORENA MEDINA MONTERO</div>
                    <div class="col">IVONNE ESMERALDA DURÁN DÍAZ</div>
                </div>
                <div class="row">
                    <div class="col">ANDY WILLIAM GUEVARA ROLDAN</div>
                    <div class="col"></div>
                    <div class="col">FERNANDO HERIBERTO MUSTO RAMÍREZ</div>
                </div>
                <div class="row">
                    <div class="col">
                        &copy; 2024 - M1_G1_Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Politica de privacidad</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

M1-G1-Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - M1_G1_Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body class="bg-dark">
    <div class="d-flex">
        <div id="sidebar">
            <div class="p-2">
                <a class="navbar-brand text-center text-light w-100 p-4 border-bottom" style="color: #9B2930!important"
                   asp-controller="Home" asp-action="Index">
                    Dulce Sabor
                </a>
            </div>
            <div id="sidebar-accordion" class="accordion">
                <div class="list-group">
                    <a data-toggle="collapse" aria-expanded="false"
                       class="list-group-item list-group-item-action bg-dark text-light"
                       asp-controller="Home" asp-action="Index"
                    >
                        <img class="icono" src="@Url.Content("~/images/home.png")" alt="Inicio"/>Inicio
                    </a>
                    <a data-toggle="collapse" aria-expanded="false"
                       class="list-group-item list-group-item-action bg-dark text-light"
                    asp-controller="Empleadoes" asp-action="Index">
                        <img class="icono" src="@Url.Content("~/images/user.png")" alt="Empleados"/>Empleados
                    </a>
                    <a class="list-group-item list-group-item-action bg-dark text-light"
                        asp-controller="Mesas" asp-action="Index">
                        <img class="icono" src="@Url.Content("~/images/table.png")" alt="Mesas"/>Mesas
                    </a>
                    <a data-toggle="collapse" aria-expanded="false"
                       class="list-group-item list-group-item-action bg-dark text-light"
                       asp-controller="Platos" asp-action="Index">
                        <img class="icono" src="@Url.Content("~/images/dish.png")" alt="Platos"/>Platos
                    </a>
                    <a data-toggle="collapse" aria-expanded="false"
                       class="list-group-item list-group-item-action bg-dark text-light"
                    asp-controller="Combos" asp-action="Index">
                        <img class="icono" src="@Url.Content("~/images/combo.png")" alt="Combos"/>Combos
                    </a>
                    <a data-toggle="collapse" aria-expanded="false"
                       class="list-group-item list-group-item-action bg-dark text-light"
                       asp-controller="Promociones" asp-action="Index">
                        <img class="icono" src="@Url.Content("~/images/sale.png")" alt="Promociones"/>Promociones
                    </a>
                </div>
            </div>
        </div>
        <div class="content w-100">
            <nav class="navbar navbar-dark bg-dark">
                <div class="container-xl">
                    <div class="collapse navbar-collapse show" id="navbarsExample07XL">
                      
                    </div>
                </div>
            </nav>
            <section class="p-3">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="container">
                <div class="row">
                    <div class="col">CARLOS LEONEL CASTANEDA HERNANDEZ</div>
                    <div class="col">LAURA LORENA MEDINA MONTERO</div>
                    <div class="col">IVONNE ESMERALDA DURÁN DÍAZ</div>
                </div>
                <div class="row">
                    <div class="col">ANDY WILLIAM GUEVARA ROLDAN</div>
                    <div class="col"></div>
                    <div class="col">FERNANDO HERIBERTO MUSTO RAMÍREZ</div>
                </div>
                <div class="row">
                    <div class="col">
                        &copy; 2024 - M1_G1_Admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Politica de privacidad</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>